### ISSUE TITLE
Find a suitable testing system

### ISSUE THREAD

**Issue by hmil** [CourseAdvisor/courseadvisor#89]
This is a "meta" issue to discuss possible testing solutions.

Needed:
- Test web APIs
- Integration tests (end-to-end)

Cool plus:
- Visual verification (like a page with screenshots of main pages)

Overkill:
- php unit testing

**Comment by christophetd** [comment]
I think CasperJS would be a great solution. It is focused on front-end testing and runs on PhantomJS which allows us to easily take screenshots.  See official website and https://www.lullabot.com/articles/testing-the-front-end-with-casperjs for instance

**Comment by hmil** [comment]
#91 provides a fine testing infrastructure. And has an integration test example.
Still need to write API test examples and to set up the visual verification thing (we may add a regular test case which does the screenshots but then we need to upload that somewhere from travis).

**Comment by hmil** [comment]
update: casperjs is not ideal for API testing, we should look for another framework.
Also we need a way to authenticate test users if we want to write useful tests. see #92

**Comment by hmil** [comment]
That's set:
- casper for integration
- frisby for API
- margarita to fake tequila
